In [1]:
from keras.layers import Dense,SimpleRNN,Input,LSTM
from keras.models import Model
import numpy as np

Using TensorFlow backend.


In [2]:
bot=0
human=0
base=[]

In [22]:
def ir(m):
    if m==0:
        return "rock"
    if m==1:
        return "paper"
    if m==2:
        return "scissors"
def rep(m):
    a=[1,2,0]
    return a[m]
def ell(m,num):
    q=(m+1)/(num+1)
    if q==3 or q==0.5 or q==2/3:
        return "you won"
    if q==2 or q==1/3 or q==1.5:
        return "you lost"
    if q==1:
        return "tie"
def nell(m,num):
    q=(m+1)/(num+1)
    if q==3 or q==0.5 or q==2/3:
        return 2
    if q==2 or q==1/3 or q==1.5:
        return 1
    if q==1:
        return 0
        
def inp(num):
    q=num-1
    z=np.zeros(3)
    z[q]=1
    return z
def dec(z):
    return np.argmax(z)

In [24]:
a=np.zeros((30,3))
for i in range(30):
    print("choose one 1:rock,2:paper or 3:scissors")
    num=int(input())-1
    a[i,num]=1
    m=np.random.randint(0,3)
    print("your opponent said :", ir(m), "and",ell(m,num))

choose one 1:rock,2:paper or 3:scissors
1
your opponent said : rock and tie
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : scissors and you won
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : rock and tie
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : paper and you lost
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : scissors and you won
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : scissors and you won
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : scissors and you won
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : scissors and you won
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : rock and tie
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : paper and you lost
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : rock and tie
choose one 1:rock,2:paper or 3:scissors
1
your opponent said : paper and you lost
choose one 1:rock,2:paper or 3

# len(a)

In [25]:
v=10
h=len(a)-v
chars_in  = np.zeros((h,v,3))
chars_out = np.zeros((h,3))
for i in range(h):
    for k in range(v):
        chars_in[i,k,:]=a[i+k,:]
    chars_out[i,:]=a[i+v,:]

In [26]:
a[0,:]


array([1., 0., 0.])

In [27]:
chars_out

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
inp=Input(shape=(10,3))
net=LSTM(128,activation='relu',return_sequences=True,dropout=0.3,recurrent_dropout=0.15)(inp)
net=LSTM(128,dropout=0.3,activation='relu',recurrent_dropout=0.15)(net)
net=Dense(3,activation='softmax')(net)
model=Model(inp,net)
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [29]:
model.fit(chars_in,chars_out,epochs=10)

Epoch 1/10
20/20 [==============================] - 1s 71ms/step - loss: 1.1062 - acc: 0.4000
Epoch 2/10
20/20 [==============================] - 0s 3ms/step - loss: 1.0869 - acc: 0.3000
Epoch 3/10
20/20 [==============================] - 0s 3ms/step - loss: 1.0637 - acc: 1.0000
Epoch 4/10
20/20 [==============================] - 0s 3ms/step - loss: 1.0354 - acc: 1.0000
Epoch 5/10
20/20 [==============================] - 0s 3ms/step - loss: 1.0052 - acc: 1.0000
Epoch 6/10
20/20 [==============================] - 0s 3ms/step - loss: 0.9717 - acc: 1.0000
Epoch 7/10
20/20 [==============================] - 0s 4ms/step - loss: 0.9397 - acc: 1.0000
Epoch 8/10
20/20 [==============================] - 0s 3ms/step - loss: 0.9437 - acc: 1.0000
Epoch 9/10
20/20 [==============================] - 0s 4ms/step - loss: 0.8222 - acc: 1.0000
Epoch 10/10
20/20 [==============================] - 0s 3ms/step - loss: 0.7870 - acc: 1.0000


In [30]:
rep(1)

2

In [31]:
base=a

In [32]:
base-a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
len(base)

30

In [34]:
5

5

i=30
while True:
    num=int(input())
    q=num-1
    z=np.zeros(3)
    z[q]=1
    output=model.predict(chars_in)
    d=np.zeros((h,3))
    for i in range(h):
        q=np.argmax(output[i,:])
        d[i,q]=1
    u=nell(rep(np.argmax(d[0:])),num-1)
    if u==1:
        bot+=1
        print("score : human : %d ,bot : %d"%(human,bot))
    if u==2:
        human+=1
        print("score : human : %d ,bot : %d"%(human,bot))
    base[i:]=z
    v=10
    h=len(base)-v
    chars_in  = np.zeros((h,v,3))
    chars_out = np.zeros((h,3))
    for i in range(h):
        for k in range(v):
            chars_in[i,k,:]=base[i+k,:]
        chars_out[i,:]=base[i+v,:]
    
    model.fit(chars_in,chars_out,epochs=1)
    i+=1

In [ ]:
bot/(human+bot)